# Built with Jekyll 3.6.0

# Setup
title:               María Mercedes Carranza en la Asamblea Nacional Constituyente # Título del proyecto
tagline:             'Edición Crítica Digital desde el archivo' # Subtítulo, cambiar de acuerdo con el proyecto
description:         'Una vista de la participación de María Mercedes Carranza en la Asamblea Nacional Constituyente de Colombia de 1991, a través de su archivo y el de la Asamblea'
url:                 'https://lorenzoaugust.github.io/Edici-n-digitalMMC/' # Cambiar por repositorio propio
baseurl:             '/Edici-n-digitalMMC' # Cambiar por url de base propia, también cambiar nombre de carpeta del proyecto y repositorio

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: magenta # Puede escogerse una paleta de colores entre las opciones arriba

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed
